name: Build
on:
 push:
   branches:
     - main
 pull_request:
   types: [opened, synchronize, reopened]
jobs:
  sonarqube:
    name: windows
    runs-on: windows-latest
    defaults: 
      run:
        working-directory: back
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 
      - name: Install dependencies
        run: npm i

      - name: Start server in background
        run: |
          npm run dev & 
          sleep 10

      - name: Test and coverage
        run: npm run coverage-test

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4
        with:
          projectBaseDir: back
        env:
          SONAR_TOKEN: ${{ secrets. SONARCLOUD_TOKEN }}